name: Build and Deploy our Code

on: [push, pull_request]

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: pulling our code from repo
        uses: actions/checkout@v4
      - name: setting up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.5'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt
