name: Build and Deploy our Code

on: [push, pull_request]

jobs:
  my_first_job:

    environment: 
      name: testing
    env:
      database_url: ${{secrets.database_url}}
      secret_key: ${{secrets.secret_key}}
      algorithm: ${{secrets.algorithm}}
      access_token_expire_minutes: ${{secrets.access_token_expire_minutes}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.database_password}}
          POSTGRES_DB: ${{secrets.database_name}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest

    steps:
      - name: pulling our code from repo
        uses: actions/checkout@v4
      - name: setting up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.5'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Installing dependencies
        run: pip install -r requirements.txt
